//! SplitMix64 PRNG and substream key derivation (§5.2).
//!
//! Algorithm: Sebastiano Vigna's `splitmix64.c` (public domain,
//! <https://prng.di.unimi.it/splitmix64.c>). The constants and structure are
//! from that reference. The known-answer vectors in `tests` were generated by an
//! **independent** implementation of the same public algorithm (a separate
//! Python reference, run 2026-07-18) — not copied from memory — so agreement
//! validates this implementation rather than merely restating it (§5.2: "do not
//! trust remembered constants").

const GAMMA: u64 = 0x9E37_79B9_7F4A_7C15;
const M1: u64 = 0xBF58_476D_1CE4_E5B9;
const M2: u64 = 0x94D0_49BB_1331_11EB;

/// The SplitMix64 finalizer applied to `x` (the three lines after the state
/// add). `wrapping_mul` because the multiplies are intentionally mod-2^64 (R5);
/// XOR and constant shifts are not flagged by the covenant lint.
#[inline]
#[must_use]
pub fn mix(x: u64) -> u64 {
    let z = (x ^ (x >> 30)).wrapping_mul(M1);
    let z = (z ^ (z >> 27)).wrapping_mul(M2);
    z ^ (z >> 31)
}

/// Advance `state` by GAMMA and return the next SplitMix64 output. Equivalent to
/// `mix(state + GAMMA)`; matches the reference `next()`.
#[inline]
pub fn next(state: &mut u64) -> u64 {
    *state = state.wrapping_add(GAMMA);
    mix(*state)
}

/// Substream key derivation (§5.2):
/// `mix(mix(mix(mix(mix(seed) ^ wid) ^ t) ^ cx) ^ cy)`.
/// `cx`/`cy` are `i64` reinterpreted to `u64` via two's complement (`as u64`) —
/// deterministic on every target.
#[inline]
#[must_use]
pub fn key(seed: u64, wid: u64, t: u32, cx: i64, cy: i64) -> u64 {
    let a = mix(seed);
    let b = mix(a ^ wid);
    let c = mix(b ^ u64::from(t));
    let d = mix(c ^ (cx as u64));
    mix(d ^ (cy as u64))
}

/// A SplitMix64 draw stream whose state starts at a substream `key`.
pub struct Stream {
    state: u64,
}

impl Stream {
    /// Start a stream at `key` (§5.2: "a stream's state starts at its key").
    #[inline]
    #[must_use]
    pub fn new(key: u64) -> Self {
        Self { state: key }
    }

    /// Next raw `u64`.
    #[inline]
    pub fn next_u64(&mut self) -> u64 {
        next(&mut self.state)
    }

    /// Uniform `f64` in `[1.0, 2.0)` via exact bit construction (no rounding).
    #[inline]
    pub fn next_f64_12(&mut self) -> f64 {
        let r = self.next_u64();
        f64::from_bits(0x3FF0_0000_0000_0000 | (r >> 12))
    }

    /// Uniform `f64` in `[0.0, 1.0)`: the `[1,2)` construction minus `1.0`.
    #[inline]
    pub fn next_f64_01(&mut self) -> f64 {
        self.next_f64_12() - 1.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Independent (Python) reference vectors — see module docs for provenance.
    #[test]
    fn kat_mix() {
        assert_eq!(mix(0), 0x0);
        assert_eq!(mix(1), 0x5692_161d_100b_05e5);
        assert_eq!(mix(GAMMA), 0xe220_a839_7b1d_cdaf);
    }

    #[test]
    fn kat_next_from_zero() {
        let mut s: u64 = 0;
        assert_eq!(next(&mut s), 0xe220_a839_7b1d_cdaf);
        assert_eq!(next(&mut s), 0x6e78_9e6a_a1b9_65f4);
        assert_eq!(next(&mut s), 0x06c4_5d18_8009_454f);
        assert_eq!(next(&mut s), 0xf88b_b8a8_724c_81ec);
        assert_eq!(s, 0x78dd_e6e5_fd29_f054);
    }

    #[test]
    fn kat_key() {
        assert_eq!(key(0, 1, 0, 0, 0), 0x683b_5fc0_ca80_3dc3);
        assert_eq!(
            key(0x0123_4567_89AB_CDEF, 3, 2, 5, -7),
            0xe6ac_ac8d_7217_14bb
        );
    }

    #[test]
    fn uniform_ranges() {
        // Exhaustive-ish sanity: constructions land in the documented ranges.
        let mut s = Stream::new(0xDEAD_BEEF_CAFE_BABE);
        for _ in 0..10_000 {
            let a = s.next_f64_12();
            assert!((1.0..2.0).contains(&a));
            let b = s.next_f64_01();
            assert!((0.0..1.0).contains(&b));
        }
    }
}
